OBJS += kernel/kernel.o \
	kernel/terminal/initialize_terminal.o \
	kernel/terminal/terminal_clear_screen.o \
	kernel/terminal/terminal_putchar.o \
	kernel/terminal/terminal_putentryat.o \
	kernel/terminal/terminal_putstr.o \
	kernel/terminal/terminal_setcolor.o \
	kernel/terminal/terminal_write.o \
	kernel/terminal/vga_entry.o
