HEADERS += \
inc/GDT.h \
inc/asm.h \
inc/io.h \
inc/kernel.h \
inc/lib.h \
inc/list.h \
inc/multiboot2.h \
inc/page.h \
inc/panic.h \
inc/position.h \
inc/printk.h \
inc/shell.h \
inc/tty.h \
inc/typedef.h \
inc/vga.h \
